rtspDisable: no
protocols: [tcp]
rtspAddress: 0.0.0.0:8554

rtmpDisable: yes

hlsDisable: no
hlsAddress: 0.0.0.0:8888
hlsSegmentCount: 4
hlsSegmentDuration: 2s

paths:
  all:
    fallback:
    disablePublisherOverride: no

  ring:
    source: publisher
    runOnDemand: node /ring-hassio/ring_hassio/main.mjs -acodec aac -vcodec copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
    runOnDemandRestart: yes
    runOnDemandStartTimeout: 20s
    runOnDemandCloseAfter: 5s